import '../../../lib/Justfile'

base_image_url := "https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2025-05-13/2025-05-13-raspios-bookworm-arm64-lite.img.xz"
base_image_sha256 := "62d025b9bc7ca0e1facfec74ae56ac13978b6745c58177f081d39fbb8041ed45"
base_image_name := "raspios:2025-05-13-bookworm-arm64-lite"
