import '../../../lib/Justfile'

base_image_url := "https://downloads.raspberrypi.com/raspios_lite_armhf/images/raspios_lite_armhf-2025-05-13/2025-05-13-raspios-bookworm-armhf-lite.img.xz"
base_image_sha256 := "a73d68b618c3ca40190c1aa04005a4dafcf32bc861c36c0d1fc6ddc48a370b6e"
base_image_name := "raspios:2025-05-13-bookworm-armhf-lite"