import '../../../lib/Justfile'

base_image_url := "https://github.com/elk-audio/elk-pi/releases/download/1.0.0/elkpi-audio-os-image-raspberrypi4-64-v1.0.0.wic.bz2"
base_image_sha256 := "a97216f6d19c381b39ce2fd731788e548032e46011c23c26be67d71a9d916515"
base_image_name := "elkpi:1.0.0"