FROM elkpi:1.0.0

# Enable read-only access to root file system on boot
RUN elk_system_utils --ro-rootfs enable

# Start sushi automatically
RUN systemctl enable sushi

# Connect midi to sushi automatically
# "USB MIDI Interface" is the name of my midi adapter
RUN systemctl enable midi-connections
RUN sed -i 's/midi-keyboard/USB MIDI Interface/g' /usr/bin/connect-midi-apps

# Copy config
ADD play_lv2_faust.json /home/mind/config_files/play_lv2_faust.json
RUN sed -i 's/empty.json/play_lv2_faust.json/g' /lib/systemd/system/sushi.service

# Copy lv2 plugin
ADD faust.lv2 /usr/lib/lv2/faust.lv2
RUN sed -i '/^\[Service\]/a Environment="LV2_PATH=/usr/lib/lv2"' /lib/systemd/system/sushi.service